include/qemu/bitops.h: fix the preprocessor not recognizing the `sizeof` operator
cat make_error.log
In file included from /home/wujing/code/qemu-2.8+dfsg/include/qemu/hbitmap.h:15:0,
                 from /home/wujing/code/qemu-2.8+dfsg/include/block/dirty-bitmap.h:5,
                 from /home/wujing/code/qemu-2.8+dfsg/include/block/block.h:9,
                 from /home/wujing/code/qemu-2.8+dfsg/include/block/block_int.h:28,
                 from /home/wujing/code/qemu-2.8+dfsg/block/raw-posix.c:30:
/usr/include/linux/swab.h: In function ‘__swab’:
/home/wujing/code/qemu-2.8+dfsg/include/qemu/bitops.h:20:34: warning: "sizeof" is not defined [-Wundef]
 #define BITS_PER_LONG           (sizeof (unsigned long) * BITS_PER_BYTE)
                                  ^
/home/wujing/code/qemu-2.8+dfsg/include/qemu/bitops.h:20:41: error: missing binary operator before token "("
 #define BITS_PER_LONG           (sizeof (unsigned long) * BITS_PER_BYTE)
                                         ^
make: *** [block/raw-posix.o] Error 1
make: *** 正在等待未完成的任务....

apt policy gcc
gcc:
  已安装：4:6.3.0-4
  候选： 4:6.3.0-4
  版本列表：
 *** 4:6.3.0-4 500
        500 http://archive.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

- [qemu 安装 recipe for target 'block/file-posix.o' failed error:
missing binary operator before token
"(](https://blog.csdn.net/FJDJFKDJFKDJFKD/article/details/105982709)

Signed-off-by: wujing <realwujing@qq.com>
Signed-off-by: QiLiang Yuan <yuanql9@chinatelecom.cn>